global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using Order.Domain.Contract.Models.Order;
global using Order.Domain.Entities;
global using Order.Domain.Contract.Models.OrderItem;
global using Order.Domain.Entities.BaseInfo;